import 'package:playground/screen/main/tab/mail/vo/vo_mail.dart';

final mailList = [
  Mail(0, '안녕하세요?', '저는 김동욱이라고 합니다.저는 김동욱이라고 합니다.저는 김동욱이라고 합니다.저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now(), null),
  Mail(1, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now(), null),
  Mail(2, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(minutes: 7)), null),
  Mail(3, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(minutes: 10)), null),
  Mail(4, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(minutes: 40)), null),
  Mail(5, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 2, minutes: 3)), null),
  Mail(6, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 2, minutes: 19)), null),
  Mail(7, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 3)), null),
  Mail(8, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 3, minutes: 40)), null),
  Mail(9, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 6, minutes: 18)), null),
  Mail(10, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 7, minutes: 31)), null),
  Mail(11, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 9, minutes: 23)), null),
  Mail(12, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 12, minutes: 15)), null),
  Mail(13, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 15, minutes: 16)), null),
  Mail(14, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 18, minutes: 19)), null),
  Mail(15, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 18, minutes: 59)), null),
  Mail(16, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 19, minutes: 49)), null),
  Mail(17, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 20, minutes: 33)), null),
  Mail(18, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(hours: 21, minutes: 13)), null),
  Mail(19, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(days: 3)), null),
  Mail(20, '안녕하세요?', '저는 김동욱이라고 합니다.', '김동욱', '홍길동', DateTime.now().subtract(Duration(days: 400)), null),
];
