import 'package:playground/screen/main/tab/board/vo/vo_board.dart';

final boardList = [
  Board('반갑습니다0', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다1', '반가워요', createdBy: '김동욱', likeCount: 4),
  Board('반갑습니다2', '반가워요', createdBy: '김동욱', likeCount: 1),
  Board('반갑습니다3', '반가워요', createdBy: '김동욱', likeCount: 7),
  Board('반갑습니다4', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다5', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다6', '반가워요', createdBy: '김동욱', likeCount: 9),
  Board('반갑습니다7', '반가워요', createdBy: '김동욱', likeCount: 112),
  Board('반갑습니다8', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다9', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다10', '반가워요', createdBy: '김동욱', likeCount: 53),
  Board('반갑습니다11', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다12', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다13', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다14', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다15', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다16', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다17', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다18', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다19', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다20', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다21', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다22', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다23', '반가워요', createdBy: '김동욱', likeCount: 0),
  Board('반갑습니다24', '반가워요', createdBy: '김동욱', likeCount: 0),
];